#!/usr/bin/env bash
set -euo pipefail

CAR_HOST="${CAR_HOST:-pi@192.168.1.11}"
CAR_DIR="${CAR_DIR:-/home/pi/temp/inspection_robot}"
RUN_MODE="${RUN_MODE:-robot}"
PORT="${PORT:-5000}"
LINE_FOLLOW_ENABLED="${LINE_FOLLOW_ENABLED:-0}"  # 强制禁用循线，避免干扰测试
TRANSFER_LINE_ENABLED="${TRANSFER_LINE_ENABLED:-0}"  # 禁用货架间巡线，采用直行+姿态纠偏
# Recognition: keep AprilTag only. OCR (heavy on the Pi) and colour attribute
# labelling are off by default; set ENABLE_OCR=1 / ENABLE_COLOR=1 to restore.
ENABLE_OCR="${ENABLE_OCR:-0}"
ENABLE_COLOR="${ENABLE_COLOR:-0}"
SMOOTH_CRUISE_ENABLED="${SMOOTH_CRUISE_ENABLED:-1}"
CRUISE_SPEED="${CRUISE_SPEED:-22}"
CRUISE_TICK_SECONDS="${CRUISE_TICK_SECONDS:-0.03}"
TIMED_STOP_SCAN_ENABLED="${TIMED_STOP_SCAN_ENABLED:-0}"
TIMED_STOP_SCAN_SPEED="${TIMED_STOP_SCAN_SPEED:-15}"
TIMED_STOP_SCAN_DRIVE_SECONDS="${TIMED_STOP_SCAN_DRIVE_SECONDS:-0.8}"
TIMED_STOP_SCAN_SETTLE_SECONDS="${TIMED_STOP_SCAN_SETTLE_SECONDS:-0.2}"
MOTION_GUARD_POLL_SECONDS="${MOTION_GUARD_POLL_SECONDS:-0.005}"
# One motor write per command tightens the boundary poll cadence (~0.01s vs
# ~0.03s) so the car reacts to the tape sooner and overshoots less.
ROBOT_COMMAND_REPEAT="${ROBOT_COMMAND_REPEAT:-1}"
BOUNDARY_MIN_BLACK_SENSORS="${BOUNDARY_MIN_BLACK_SENSORS:-1}"
# confirm=1: we already stop on the candidate; a live re-read could drop a real
# boundary if the car coasts onto white, letting it drive out of bounds.
BOUNDARY_CONFIRM_SAMPLES="${BOUNDARY_CONFIRM_SAMPLES:-1}"
BOUNDARY_CONFIRM_GAP_SECONDS="${BOUNDARY_CONFIRM_GAP_SECONDS:-0.0}"
BOUNDARY_WINDOW_SECONDS="${BOUNDARY_WINDOW_SECONDS:-0.25}"
# backward (not forward): after confirming the tape, back off the line before
# turning instead of driving further across it (the #1 out-of-bounds cause).
BOUNDARY_RETREAT_COMMAND="${BOUNDARY_RETREAT_COMMAND:-backward}"
BOUNDARY_RETREAT_SECONDS="${BOUNDARY_RETREAT_SECONDS:-0.14}"
HEADING_HOLD_TOLERANCE_DEG="${HEADING_HOLD_TOLERANCE_DEG:-1.2}"
MPU6050_YAW_DEADBAND_DPS="${MPU6050_YAW_DEADBAND_DPS:-0.7}"
MPU6050_YAW_LEAK_PER_SECOND="${MPU6050_YAW_LEAK_PER_SECOND:-0.15}"
HEADING_HOLD_CORRECTION_SPEED="${HEADING_HOLD_CORRECTION_SPEED:-16}"
HEADING_HOLD_SPEED_GAIN="${HEADING_HOLD_SPEED_GAIN:-3.0}"
HEADING_HOLD_MIN_CORRECTION_SPEED="${HEADING_HOLD_MIN_CORRECTION_SPEED:-6}"
HEADING_HOLD_MAX_SPEED_FRACTION="${HEADING_HOLD_MAX_SPEED_FRACTION:-0.8}"
HEADING_HOLD_MIN_INTERVAL_SECONDS="${HEADING_HOLD_MIN_INTERVAL_SECONDS:-0.05}"
OBJECT_PRESENCE_COOLDOWN_SECONDS="${OBJECT_PRESENCE_COOLDOWN_SECONDS:-1.5}"
OBJECT_PRESENCE_MIN_AREA_RATIO="${OBJECT_PRESENCE_MIN_AREA_RATIO:-0.008}"
BLOCKED_DISTANCE_MM="${BLOCKED_DISTANCE_MM:-100}"
CLEAR_DISTANCE_MM="${CLEAR_DISTANCE_MM:-160}"
BLOCKED_SAMPLES="${BLOCKED_SAMPLES:-3}"
ROBOT_PIPER_DIR="${ROBOT_PIPER_DIR:-/home/pi/temp/piper}"
ROBOT_PIPER_MODEL="${ROBOT_PIPER_MODEL:-$ROBOT_PIPER_DIR/zh_CN-huayan-x_low.onnx}"

case "$RUN_MODE" in
  simulate|robot)
    ;;
  *)
    echo "RUN_MODE 只能是 simulate 或 robot。" >&2
    exit 1
    ;;
esac

ssh "$CAR_HOST" "
cd '$CAR_DIR'
if [ -x .venv/bin/python ] && .venv/bin/python -c 'import sys; raise SystemExit(sys.version_info < (3, 10))' >/dev/null 2>&1; then
  PYTHON_CMD=\"\$PWD/.venv/bin/python\"
else
  PYTHON_CMD=\$(for candidate in python3.13 python3.12 python3.11 python3.10 python3 python; do
    if command -v \"\$candidate\" >/dev/null 2>&1 && \"\$candidate\" -c 'import sys; raise SystemExit(sys.version_info < (3, 10))' >/dev/null 2>&1; then
      printf '%s' \"\$candidate\"
      exit 0
    fi
  done)
fi
if [ -z \"\$PYTHON_CMD\" ]; then
  echo '未找到可用的 Python 3.10+ 解释器。' >&2
  exit 1
fi
if command -v fuser >/dev/null 2>&1; then
  fuser -k '$PORT'/tcp >/dev/null 2>&1 || true
  sleep 0.5
fi
PYTHON_REAL=\$(\"\$PYTHON_CMD\" -c 'import sys; print(sys.executable)')
echo \"Using Python: \$PYTHON_REAL\"
if [ \"\$PYTHON_CMD\" = \"\$PWD/.venv/bin/python\" ]; then
  export VIRTUAL_ENV=\"\$PWD/.venv\"
  export PATH=\"\$VIRTUAL_ENV/bin:\$PATH\"
fi
if [ -x '$ROBOT_PIPER_DIR/piper' ]; then
  export PATH='$ROBOT_PIPER_DIR':\"\$PATH\"
fi
if [ '$RUN_MODE' = 'robot' ] && [ -x /home/pi/project_demo/raspbot/killprocess.sh ]; then
  /bin/sh /home/pi/project_demo/raspbot/killprocess.sh || true
fi
RUN_MODE='$RUN_MODE' LINE_FOLLOW_ENABLED='$LINE_FOLLOW_ENABLED' TRANSFER_LINE_ENABLED='$TRANSFER_LINE_ENABLED' ENABLE_OCR='$ENABLE_OCR' ENABLE_COLOR='$ENABLE_COLOR' SMOOTH_CRUISE_ENABLED='$SMOOTH_CRUISE_ENABLED' CRUISE_SPEED='$CRUISE_SPEED' CRUISE_TICK_SECONDS='$CRUISE_TICK_SECONDS' TIMED_STOP_SCAN_ENABLED='$TIMED_STOP_SCAN_ENABLED' TIMED_STOP_SCAN_SPEED='$TIMED_STOP_SCAN_SPEED' TIMED_STOP_SCAN_DRIVE_SECONDS='$TIMED_STOP_SCAN_DRIVE_SECONDS' TIMED_STOP_SCAN_SETTLE_SECONDS='$TIMED_STOP_SCAN_SETTLE_SECONDS' MOTION_GUARD_POLL_SECONDS='$MOTION_GUARD_POLL_SECONDS' ROBOT_COMMAND_REPEAT='$ROBOT_COMMAND_REPEAT' BOUNDARY_MIN_BLACK_SENSORS='$BOUNDARY_MIN_BLACK_SENSORS' BOUNDARY_CONFIRM_SAMPLES='$BOUNDARY_CONFIRM_SAMPLES' BOUNDARY_CONFIRM_GAP_SECONDS='$BOUNDARY_CONFIRM_GAP_SECONDS' BOUNDARY_WINDOW_SECONDS='$BOUNDARY_WINDOW_SECONDS' BOUNDARY_RETREAT_COMMAND='$BOUNDARY_RETREAT_COMMAND' BOUNDARY_RETREAT_SECONDS='$BOUNDARY_RETREAT_SECONDS' HEADING_HOLD_TOLERANCE_DEG='$HEADING_HOLD_TOLERANCE_DEG' MPU6050_YAW_DEADBAND_DPS='$MPU6050_YAW_DEADBAND_DPS' MPU6050_YAW_LEAK_PER_SECOND='$MPU6050_YAW_LEAK_PER_SECOND' HEADING_HOLD_CORRECTION_SPEED='$HEADING_HOLD_CORRECTION_SPEED' HEADING_HOLD_SPEED_GAIN='$HEADING_HOLD_SPEED_GAIN' HEADING_HOLD_MIN_CORRECTION_SPEED='$HEADING_HOLD_MIN_CORRECTION_SPEED' HEADING_HOLD_MAX_SPEED_FRACTION='$HEADING_HOLD_MAX_SPEED_FRACTION' HEADING_HOLD_MIN_INTERVAL_SECONDS='$HEADING_HOLD_MIN_INTERVAL_SECONDS' OBJECT_PRESENCE_COOLDOWN_SECONDS='$OBJECT_PRESENCE_COOLDOWN_SECONDS' OBJECT_PRESENCE_MIN_AREA_RATIO='$OBJECT_PRESENCE_MIN_AREA_RATIO' BLOCKED_DISTANCE_MM='$BLOCKED_DISTANCE_MM' CLEAR_DISTANCE_MM='$CLEAR_DISTANCE_MM' BLOCKED_SAMPLES='$BLOCKED_SAMPLES' ROBOT_PIPER_MODEL='$ROBOT_PIPER_MODEL' PORT='$PORT' FLAGS_use_mkldnn=0 OMP_NUM_THREADS=1 CPU_NUM=1 nohup \"\$PYTHON_CMD\" app.py > app.log 2>&1 & echo \$!
"
echo "Started on $CAR_HOST:$CAR_DIR with RUN_MODE=$RUN_MODE, LINE_FOLLOW_ENABLED=$LINE_FOLLOW_ENABLED, TRANSFER_LINE_ENABLED=$TRANSFER_LINE_ENABLED, ENABLE_OCR=$ENABLE_OCR, ENABLE_COLOR=$ENABLE_COLOR, SMOOTH_CRUISE_ENABLED=$SMOOTH_CRUISE_ENABLED, TIMED_STOP_SCAN_ENABLED=$TIMED_STOP_SCAN_ENABLED, TIMED_STOP_SCAN_SPEED=$TIMED_STOP_SCAN_SPEED, TIMED_STOP_SCAN_DRIVE_SECONDS=$TIMED_STOP_SCAN_DRIVE_SECONDS, MOTION_GUARD_POLL_SECONDS=$MOTION_GUARD_POLL_SECONDS, BOUNDARY_MIN_BLACK_SENSORS=$BOUNDARY_MIN_BLACK_SENSORS, BOUNDARY_CONFIRM_SAMPLES=$BOUNDARY_CONFIRM_SAMPLES, BOUNDARY_CONFIRM_GAP_SECONDS=$BOUNDARY_CONFIRM_GAP_SECONDS, BOUNDARY_WINDOW_SECONDS=$BOUNDARY_WINDOW_SECONDS, BOUNDARY_RETREAT_COMMAND=$BOUNDARY_RETREAT_COMMAND, ROBOT_PIPER_MODEL=$ROBOT_PIPER_MODEL, PORT=$PORT"
